# Generated by Django 4.1.7 on 2023-05-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45, verbose_name='Marca')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(choices=[('Construccion', 'Construcción'), ('Electricidad', 'Electricidad'), ('Herramientas Manual', 'Herramientas Manual'), ('Plomeria y Tuberias', 'Plomeria y Tuberias')], max_length=45, verbose_name='Subcategoria')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Subcategorias',
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(max_length=45, verbose_name='Unidades')),
                ('medida', models.CharField(choices=[('1', 'Pulgada'), ('2', 'Centimetro'), ('3', 'Milimetros'), ('4', 'Kilos'), ('5', 'Miligramos'), ('6', 'Libras')], max_length=45, verbose_name='Medida')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('precio', models.CharField(max_length=45, verbose_name='Precio')),
                ('color', models.CharField(choices=[('1', 'Azul'), ('2', 'Rojo'), ('3', 'Amarillo'), ('4', 'Verde'), ('5', 'Negro')], max_length=45, verbose_name='Color')),
                ('presentacion', models.CharField(choices=[('1', 'Bolsa'), ('2', 'Caja')], max_length=45, verbose_name='Presentacion')),
                ('material', models.CharField(choices=[('1', 'Metal'), ('2', 'Plastico'), ('3', 'Hierro')], max_length=45, verbose_name='Material')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='producto.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Marca', to='producto.marca')),
                ('unidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidades', to='producto.unidades')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.subcategoria'),
        ),
    ]
