# Generated by Django 4.1.7 on 2023-05-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('ventas', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.PositiveIntegerField(max_length=45, verbose_name='Precio de compra')),
                ('precio_venta', models.PositiveIntegerField(max_length=45, verbose_name='Precio de venta')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Detalles de compras',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(max_length=45, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Nombre')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name_plural': 'Detalles de ventas',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(max_length=45, verbose_name='Cantidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=45, verbose_name='Estado')),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_egreso.detalle_compra', verbose_name='Detalle compra')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_egreso.detalle_venta', verbose_name='Detalle venta')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
