# Generated by Django 4.1.7 on 2023-05-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha de Inicio')),
                ('valor', models.IntegerField(max_length=45, verbose_name='Valor')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Cuentas Pendientes',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, help_text='MM/DD/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=15, verbose_name='Estado')),
                ('idcuentapendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.cuenta_pendiente', verbose_name='Cuenta Pendiente')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
